<?php

// app/Models/JournalMain.php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;

class JournalMain extends Model
{
    protected $table = 'journal_main';
    public $timestamps = false;
    protected $primaryKey = 'id'; // even though composite, Eloquent needs one

    /**
     * The attributes that are mass assignable.
     */
    protected $fillable = [
        'id',
        'period',
        'journal_id',
        'post_date',
        'post_time',
        'store_id',
        'journal_status_id',
        'production_status_id',
        'description',
        'closed',
        'closed_date',
        'exported',
        'printed',
        'freight',
        'discount',
        'shipper_code',
        'terms',
        'sales_tax',
        'tax_auths',
        'total_amount',
        'currencies_code',
        'currencies_value',
        'so_po_ref_id',
        'purchase_invoice_id',
        'purch_order_id',
        'purch_order_date',
        'recur_id',
        'admin_id',
        'rep_id',
        'waiting',
        'gl_acct_id',
        'bill_acct_id',
        'bill_address_id',
        'bill_primary_name',
        'bill_contact',
        'bill_address1',
        'bill_address2',
        'bill_city_town',
        'bill_state_province',
        'bill_postal_code',
        'bill_country_code',
        'bill_telephone1',
        'bill_email',
        'bill_gstn_no',
        'bill_uin_no',
        'ship_acct_id',
        'ship_address_id',
        'ship_primary_name',
        'ship_contact',
        'ship_address1',
        'ship_address2',
        'ship_city_town',
        'ship_state_province',
        'ship_postal_code',
        'ship_country_code',
        'ship_telephone1',
        'ship_email',
        'ship_gstn_no',
        'ship_uin_no',
        'terminal_date',
        'drop_ship',
        'mdi_special_instructions',
        'despatch_inst',
        'mdi_processed_status',
        'my_excise_id',
        'mytax_CST',
        'mdi_approved',
        'mdi_approved_by',
        'mdi_approved_at',
        'mdi_cust_ecc',
        'packed_weight',
        'mode_of_despatch',
        'removal_date',
        'removal_time',
        'buyers_range',
        'division',
        'collectorate',
        'tin_number',
        'documents',
        'use_address',
        'footer_notes',
        'number_of_cartons',
        'serial_of_cartons',
        'form_status',
        'form_desc',
        'awb_number',
        'ofb_awb_no',
        'inv_delivery_date',
        'ofb_delivery_date',
        'ofb_courier_name',
        'courier_reg_id',
        'apply_cod',
        'hold_report_status',
        'road_permit_required',
        'road_permit_formno',
        'is_scanned',
        'order_type',
        'cur_total',
        'excise_amt_export',
        'gross_weight',
        'net_weight',
        'size',
        'volume_weight',
        'remarks_export',
        'port_of_discharge',
        'final_destination',
        'central_excise_licence_num',
        'ct3_num',
        'ct3_num_date',
        'bill_telephone3',
        'ship_telephone3',
        'mdi_cus_file_number',
        'po_sales_tax',
        'po_excise',
        'po_freight',
        'po_payment_terms',
        'po_delivery_terms',
        'po_transport_mode',
        'origin_criterion',
        'inco_terms',
        'inco_terms_city',
        'po_p_and_f',
        'p_and_f',
        'po_g_and_w',
        'po_ordered_by',
        'gst_amt_export',
        'sez_applicable',
        'quot_type',
        'print_total',
        'transporter_id',
        'trans_distance',
        'json_generated',
        'select_terms',
        'select_sign',
        'converted_from',
        'bill_to_address',
        'ship_to_address',
        'gsp_required',
        'mdi_bank',
        'previous_payment',
        'schedule_num',
        'po_checked_by',
        'po_discount_amt',
        'form_a_num',
        'tcs',
        'ttl_pmt_rcvd_vn_invcd',
        'tcs_percent',
        'zero_rated_supply',
        'irn',
        'ack_no',
        'ack_date',
        'einv_category',
        'signed_qr_code',
        'other_condition',
        'kits_issuance',
        'is_ops_approved',
        'is_ops_revised',
        'approval_remarks',
        'purchase_shipping_date',
        'attached_order_file_name',
        'is_editable',
    ];

    /**
     * Casts
     */
    protected $casts = [
        'post_date'            => 'date',
        'closed_date'          => 'date',
        'purch_order_date'     => 'date',
        'mdi_approved_at'      => 'datetime',
        'removal_date'         => 'datetime',
        'ct3_num_date'         => 'date',
        'inv_delivery_date'    => 'date',
        'ofb_delivery_date'    => 'date',
        'ack_date'             => 'datetime',
        'purchase_shipping_date' => 'date',
        'closed'               => 'boolean',
        'drop_ship'            => 'boolean',
        'exported'             => 'boolean',
        'apply_cod'            => 'boolean',
        'is_scanned'           => 'boolean',
        'sez_applicable'       => 'boolean',
        'gsp_required'         => 'boolean',
        'json_generated'       => 'boolean',
        'zero_rated_supply'    => 'boolean',
        'kits_issuance'        => 'boolean',
        'is_ops_approved'      => 'boolean',
        'is_ops_revised'       => 'boolean',
    ];

    /**
     * Relationships
     */
    public function contact()
    {
        return $this->belongsTo(Contact::class, 'bill_acct_id', 'id');
    }

    public function shipContact()
    {
        return $this->belongsTo(Contact::class, 'ship_acct_id', 'id');
    }
}